version: '3'

services: 
    # nginx:
    #     depends_on: web-server
    #     restart: always
    #     build:
    #         context: ./nginx
    #         dockerfile: Dockerfile.dev
    #     ports:
    #         - '8080:80'
    web-server:
        build:
            context: ./web-server
            dockerfile: Dockerfile.dev
        volumes: 
            - ./web-server:/app
        ports:
            - '3000:5000'

        